### ISSUE TITLE
Suggestion: split out MvvmLightCore out of MvvmLightLibs

### ISSUE THREAD

**Issue by professor-k** [lbugnion/mvvmlight#10]
What about splitting main library into separate nuget (e.g. MvvmLightCore) from extras? It feels like it's going to be pretty easy to make that one Standard 1.0, and current MvvmLight can have that one as dependency. Not sure about common usage profile, but project I'm trying to figure out at the moment doesn't use any Extras, still have to carry reference for CommonServiceLocator, System.Windows.Ineractivity and Extras itself. All of that staff was shipped along with app, even that it wasn't actually used anywhere.

**Comment by lbugnion** [comment]
Hi,

There is a package for .NET standard 1.0 where I removed the dependency to CommonServiceLocator. It's still preview but I am trying to release a stable version by the end of this weekend.

http://www.mvvmlight.net/std10

Laurent

**Comment by professor-k** [comment]
Thank you, I'll look into it!

...And thank you for great work, BTW!

**Comment by lbugnion** [comment]
Closing as commented above.
