### ISSUE TITLE
In 2021, should we still using this library?

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [lbugnion/mvvmlight#101]
I'm new to WPF MVVM pattern and plan to use it in my application. I searched around and found mvvmlight. The corresponding PluralSight video is great and I learned a lot from it. However, the project seems halted its development and there is no updates for almost 2 years. I want to know should I still go with it in 2021? Are there any better alternatives? Thanks.

**Comment by floppydisk525** [comment]
Here's a video from Laurent from 2018 in Prague where he talks about porting MVVM Light to .Net Standard 2.0, which will work w/ today's current .Net 5 release (.net core 5).  https://github.com/lbugnion/sample-2018-updateprag

Another option is the .net toolkit:  https://github.com/windows-toolkit/MVVM-Samples  
I believe it was written in mind to be like or similar to MVVM Light.  It does have more features than what MVVM light has.  Depends on what you want to do.  

I don't think you can go wrong choosing either.

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Thanks for the reply! I'll take a look at the suggested framework.
