### ISSUE TITLE
Suggestion: Consider making ViewModelBase and ObservableObject into partial classes.

### ISSUE THREAD

**Issue by babgev** [lbugnion/mvvmlight#12]
I think it would help us in extending the toolkit to fit our specific needs.

**Comment by IsmailHassani** [comment]
I noticed that this pre is only available in single/shared project libraries. It doesn't work between separate assemblies (netstandard 2.0) . Why don't you use inheritance? I moved from partial classes to inheritance a while ago, and have to say with netstandard i'm glad i did.

**Comment by lbugnion** [comment]
As @IsmailHassani mentions, this is not practical because two partial classes need to reside in the same assembly. Thus partial classes are not a suitable mechanism to extend classes. I regret that because I think it would be quite elegant.
