### ISSUE TITLE
why I call cleaup() but some list have value????

### ISSUE THREAD

**Issue by windsOne** [lbugnion/mvvmlight#13]
![image](https://user-images.githubusercontent.com/14890297/34249721-aca10efe-e675-11e7-89c4-a22566b1a4a0.png)

**Comment by lbugnion** [comment]
Without a clear description of the issue and if possible a repro, I am not sure what to do with this issue. Please elaborate.

**Comment by windsOne** [comment]
This is the messenger registered in the constructor in the view model. After the viewModel has been used, I re-create an instance of this class and continue registering. Before each declaration, I call the cleanup method

![2](https://user-images.githubusercontent.com/14890297/34281918-dd128cc0-e6fc-11e7-8ae7-5928bf14fd6e.png)

![2](https://user-images.githubusercontent.com/14890297/34281927-e50e2a6a-e6fc-11e7-809f-44778bdda610.png)


but  i see Default value still have

**Comment by windsOne** [comment]
help me   please help me see

**Comment by lbugnion** [comment]
This issue is not clear. If you feel that this is incorrect, please reopen with a better description and a repro showing what you mean. Thanks
