### ISSUE TITLE
netstandard 2

### ISSUE THREAD

**Issue by tuath** [lbugnion/mvvmlight#2]
Bonjour du Quebec!

Quick question - can we expect netstandard 2 compliance with next release ? it would fix one warning my clients get out of this package and put of source of doubts (when problems arise) away...

Severity	Code	Description	Project	File	Line	Suppression State
Warning	NU1701	Package 'MvvmLightLibs 5.3.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.	ToDoStudio	C:\Users\erikr\Source\Repos\TodoStudio\ToDoStudio\ToDoStudio\ToDoStudio.csproj	1

**Comment by jfevia** [comment]
I second this, came searching for NETStandard 2.0 support since it's been released.

**Comment by lbugnion** [comment]
Hi, there is a preview package available, sew http://mvvmlight.net/std10.

Thanks
Laurent

**Comment by tuath** [comment]
Tried out the new package and things seem to work fine ! I didn't use the mvvmlight servicelocator pattern (using autofac) and so had no code changes. 

Thanks !

**Comment by lbugnion** [comment]
Good to know, thanks for the feedback

Sent from my Windows 10 phone
