### ISSUE TITLE
ObservableRecyclerAdapter crashes when datasource is changed outside of Ui thread

### ISSUE THREAD

**Issue by ChristophvanderFecht** [lbugnion/mvvmlight#27]
Hi!

I am using the ObservableRecyclerAdapter to bind my view against an ObservableCollection<T> in my ViewModel.
When I am updating the collection inside of my view model my code crashes and tells my that I have to do the changes on the UI Thread.

How can i do that? Or better question, what method do I need to invoke?

Currently I am invoking all methods to setup the ObservableRecyclerAdapter and the BindViewHolder method, but no success till now. 

Thx for your help!

PS. using async/await pattern is not an option.

**Comment by robinTsl** [comment]
As you are not using Tasks (aync/await) an alternative option is to use some sort of dispatcher. A helper class is provided in MVVM Light that does this [DispatcherHelper.RunAsync(Action action)](https://github.com/lbugnion/mvvmlight/blob/master/GalaSoft.MvvmLight/GalaSoft.MvvmLight.Platform%20(NET45)/Threading/DispatcherHelper.cs). We prefer to inject an IDispatcher interface into our view models that has implementations per platform (for example BeginInvokeOnMainThread for [Xamarin Forms](https://docs.microsoft.com/en-gb/xamarin/ios/user-interface/ios-ui/ui-thread))

**Comment by ChristophvanderFecht** [comment]
@robinTsl Your suggestion solved my problem, thx again.
