### ISSUE TITLE
Add binding-redirects or other compatibility with CommonServiceLocator 1.4 or 2.0

### ISSUE THREAD

**Issue by Jehoel** [lbugnion/mvvmlight#3]
The CommonServiceLocator package, upon which MvvmLight takes a dependency, was updated to version 1.4 and 2.0.1 (there was no 2.0.0 version) last month: https://www.nuget.org/packages/CommonServiceLocator/

My current project which uses the latest MvvmLight package (5.3.0) is unable to build with either the 1.4 or 2.0.1.

With version 1.4, VS2017 tells me I must continue to reference version 1.3.0 specifically:

> The type 'IServiceLocator' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Practices.ServiceLocation, Version=1.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

As a quick-fix, is this something that could be resolved with a binding redirect?

Alternatively, the NuGet dependencies could be restricted to be exactly `== 1.3.0.0` instead of the current `>= 1.3.0`, so NuGet won't upgrade to 1.4.0 or 2.0.1.

With version 2.0, the internal layout of the CommonServiceLocator library is significantly overhauled and namespaces have been renamed, breaking both the assembly reference, but also type resolution.

Would it be possible to remove the dependency on CommonServiceLocator entirely? I'm not familiar with MvvmLight's internals, but doing so would help, methinks.

**Comment by lbugnion** [comment]
As an alternative for the moment you might be able to use the MVVM Light for .NET Standard which does not use CommonServiceLocator. I will check why it is picking up the wrong version. I am considering removing CommonServiceLocator completely, but it would be a breaking change so there are a lot of things to consider. https://www.nuget.org/packages/MvvmLightLibsStd10

**Comment by lbugnion** [comment]
Put this on the backlog for V5.4 which I am working on now.

**Comment by lbugnion** [comment]
Added support for CommonServiceLocator V2.1 in MVVM Light V5.4.1

**Comment by MrYossu** [comment]
@lbugnion I tried creating a new VS WPF project, and adding MVVMLight from Nuget. You end up with CommonServiceLocator version 2.0.4, which you have to downgrade to 1.3.0 to get it to compile. You said you'd fixed it, but it still doesn't work out of the box.

Please could you clarify? Thanks
