### ISSUE TITLE
Problem with ListView binding

### ISSUE THREAD

**Issue by sonnenschein123** [lbugnion/mvvmlight#36]
Hello, 

I write a tool with mvvm light, my MainForm xaml code contains a ListView like this:

    <ListView AlternationCount="2" ScrollViewer.CanContentScroll="True" ScrollViewer.HorizontalScrollBarVisibility="Auto" ItemsSource="{Binding SQLVersionenView, Mode=TwoWay}" MinHeight="25" Grid.ColumnSpan="2" Grid.Row="1">
        <ListView.View>
            <GridView>
                <GridViewColumn Header="State">
                    <GridViewColumn.CellTemplate>
                        <DataTemplate>
                            <CheckBox IsChecked="{Binding import, Mode=TwoWay}"/>
                        </DataTemplate>
                    </GridViewColumn.CellTemplate>
                </GridViewColumn>
                <GridViewColumn Header="Version" DisplayMemberBinding="{Binding SQL_VERSION}"/>
                <GridViewColumn Header="comment" DisplayMemberBinding="{Binding COMMENT}"/>
                <GridViewColumn Header="path" DisplayMemberBinding="{Binding sql_path}"/>
            </GridView>
        </ListView.View>
    </ListView>

The binding works pretty well, but I implemented a *select all* function and this don’t do anything 

    private void selectAllPretty() {
        foreach (SQLVersionInfo tmpSQLVersionInfo in SQLVersionenView) {
            tmpSQLVersionInfo.import = true; // Just update the value
        }
    }

So I tried a little bit and found a way to get the job done: 

    private void selectAllUgly() {
        List<SQLVersionInfo> tmpSQLVersionenView = new List<SQLVersionInfo>(); // Create new list
        foreach (SQLVersionInfo tmpSQLVersionInfo in SQLVersionenView) {
            tmpSQLVersionInfo.import = true;
            tmpSQLVersionenView.Add(tmpSQLVersionInfo); // Fill the new list
        }
        SQLVersionenView = tmpSQLVersionenView; // Update the actual list
    }

So my question is, is there a third way? What have I done wrong? 

Best,
sonnenschein123

**Comment by vlm---** [comment]
Check if your class `SQLVersionInfo` implements `INotifyPropertyChanged` interface, or you can use ObservableObject from this framework as a base object.

**Comment by sonnenschein123** [comment]
Hey @vlm--- 
I implemented it with ObservableObject. 
So thanks a lot.
