### ISSUE TITLE
Update canExecute 

### ISSUE THREAD

**Issue by sonnenschein123** [lbugnion/mvvmlight#43]
Hello, 
to dis-/enable a button I use the RelayCommand with the canExecute parameter.
My problem is, in case the window is not focused, the buttons are not gone updated. If I focus the Window everything works fine. 
I tried to call the RaiseCanExecuteChanged and set keepTargetAlive true, but it wont work. 
Where is the missing link? how can I execute the function correctly?

Best, 
Sonnenschein123

**Comment by olitee** [comment]
Did you call 'RaiseCanExecuteChanged' from the main/UI thread? I seem to recall it's ignored by the UI if called from another thread.

**Comment by sonnenschein123** [comment]
Hey @olitee 
Thanks for the note. I called it from a different thread. 
Best, 
Sonnenschein123
