### ISSUE TITLE
Messenger strange behavior [BUG]

### ISSUE THREAD

**Issue by MiroslavMikus** [lbugnion/mvvmlight#55]
I have a relatively small application [here](https://github.com/MiroslavMikus/DependencyScanner). Here is the code snippet from my constructor:
![image](https://user-images.githubusercontent.com/29312172/50645646-5482ec00-0f74-11e9-9ecd-5d6a49791be6.png)

You can find the whole class [here](https://github.com/MiroslavMikus/DependencyScanner/blob/master/DependencyScanner.Standalone/Components/NugetScan/NugetScanViewModel.cs).

The problem is that the registration callback at line 58 will be executed and the callback at 62 not. The registration is exactly the same. If I switch the registrations or remove the first one the result is still the same... Somehow never going to hit the callback at line 62.

Do you have some suggestions for me? Do I miss something?

Thank you

**Comment by MiroslavMikus** [comment]
I have found a workaround:

![image](https://user-images.githubusercontent.com/29312172/50650538-088a7400-0f81-11e9-9701-f8d8e91b2bcd.png)

I have [moved](https://github.com/MiroslavMikus/DependencyScanner/commit/314060108c1ac4d4c2f5d6493aebd15ee7a30ace) all logic from lambda to a named function. Everything works fine.

Still seems like bug for me.

**Comment by MiroslavMikus** [comment]
Yeah, it's on my todo list. 

Easy stuff to do in WPF: some master-detail view like an ListView with buildings and some detail view with data-binding to the buildings view selected item.

Hard stuff: 4x one to many model like: Folder has many repositories, repository has many solutions, solution has many projects, project has many dependencies. And bould view for that... So the events are the best solution for this I was able to come with.

Maybe you have some great tipp / advice for me. Some example repo would be wellcome as well.

**Comment by Christian-Schulz** [comment]
Today i ran into the same issue. This comment is the solution.

https://github.com/lbugnion/mvvmlight/blob/4cbf77ca6fbe91f83cece8fbf288b166c54202c5/GalaSoft.MvvmLight/GalaSoft.MvvmLight%20(PCL)/Messaging/IMessenger.cs#L38-L49

**Comment by MiroslavMikus** [comment]
I didn't know that there are also weak actions. Many thanks, @Christian-Schulz. I will close this issue since it is well known and documented.
