### ISSUE TITLE
iOS Dialog service implementation based on depreciated UIAlertView

### ISSUE THREAD

**Issue by ghost** [lbugnion/mvvmlight#6]
iOS DialogService implementation is based on the depreciated UIAlertView. It should be implemented using UIAlertController.

https://developer.apple.com/documentation/uikit/uialertview
https://github.com/lbugnion/mvvmlight/blob/master/GalaSoft.MvvmLight/GalaSoft.MvvmLight.Platform (iOS)/Views/DialogService.cs

**Comment by lbugnion** [comment]
Thanks I will put that on the backlog.
