### ISSUE TITLE
Multi-targeting & package build in .NET Standard

### ISSUE THREAD

**Issue by jamesmcroft** [lbugnion/mvvmlight#64]
Currently, it appears that the management of the packaging and build of the MvvmLight NuGet packages is done with an older mechanism of doing so (NuSpec). 

While this works for the older PCL projects, .NET Standard has a very interesting feature which allows multi-targeting and NuGet package building. 

With the combination of the [MSBuild SDK Extras](https://github.com/onovotny/MSBuildSdkExtras), it's possible to completely turn on multi-targeting across the current supported platforms that MvvmLight provides. 

This is something that has been an effort in the XPlat Windows API project that I contribute towards (ref: https://github.com/XPlat-Apps/XPlat-Windows-APIs/blob/develop/XPlat.Storage/XPlat.Storage.csproj)

The NuGet packaging also comes for free within the csproj format. At the moment, the MvvmLight NuSpec file has some hard-coded parts to it which don't appear to be updated automatically as part of the current build and packaging mechanism which is currently being used.

This is something that I believe will help reduce the overhead of manual changes as well as keeping everything neat and tidy within a single .NET Standard project.

**Comment by jamesmcroft** [comment]
As a test, I created a "broken" variant of MvvmLight for .NET Standard that shows how this might work (https://github.com/jamesmcroft/mvvmlight/tree/netstandard-multi/GalaSoft.MvvmLight/GalaSoft.MvvmLight).

This wouldn't be mergable as I scraped all the code into a single project and have only made it work for .NET Standard, Xamarin and Windows (UWP). 

I believe it might require a fair bit of work to move and support all the platforms, but it is definitely possible.

**Comment by jamesmcroft** [comment]
So I did eventually get all this working, except it doesn't support the Silverlight components at https://github.com/jamesmcroft/mvvmlight.

Again, the change wouldn't be mergeable into this repo given that I've basically stripped everything out that's not needed now that the intention would be for folks to use .NET Standard unless this is a change that @lbugnion would be willing to make.

For my own peace of mind, I've created an Azure Pipeline for the forked repo which outputs the NuGet packages and I am currently distributing this on NuGet as MADE.App.MvvmLightLibs. 

As part of the changes I've made, I've merged the Android Support library into the main component. This way they can be updated as one single unit rather than two separate libraries which will make this more maintainable, however, it doesn't have to be this way. It just made more sense as in all cases where I've used MvvmLightLibs which includes an Android project, I've also taken the dependency on the Android Support component.

**Comment by michael-hawker** [comment]
@jamesmcroft I suppose this is part of what led to our MVVM Toolkit work, eh? Glad you helped start us down this journey. Should we close this issue?

Migration Guide to the MVVM Toolkit docs are here now: https://docs.microsoft.com/windows/communitytoolkit/mvvm/migratingfrommvvmlight

**Comment by jamesmcroft** [comment]
Definitely. Thanks to the work on the MVVM Toolkit, I've moved the majority of my projects over now. 

Just a few lingering ones 😅
