### ISSUE TITLE
VerifyPropertyName in UWP

### ISSUE THREAD

**Issue by ivanvs** [lbugnion/mvvmlight#7]
Hi,

We are currently working on UWP application and we have found an issue that you have already fixed. The issue in question is: https://github.com/lbugnion/mvvmlight/commit/7d400cfc4c3031f76f89b2e2ee1154c8383c65e4. 

So, I was wondering when will you release new version with this fix on NuGet?

**Comment by lbugnion** [comment]
I am working on fixing a few new things. Expecting a new *stable* Nuget in the next 2 weeks.

**Comment by ivanvs** [comment]
Thank you for your response. That sounds great and fits our planning also.
