### ISSUE TITLE
VSIX packages for Visual Studio 2019

### ISSUE THREAD

**Issue by tian666666** [lbugnion/mvvmlight#75]
when vsix packages support to VS2019?

**Comment by a5ync** [comment]
@tian666666 there is already a PR with 2019 version.
https://github.com/lbugnion/mvvmlight/pull/72

**Comment by ElectroMyStyle** [comment]
> @tian666666 there is already a PR with 2019 version.
> #72
You do not know why this is not available in the marketplace?

https://marketplace.visualstudio.com/items?itemName=LaurentBugnion.MVVMLightforVS2019

**Comment by tian666666** [comment]
> > @tian666666 there is already a PR with 2019 version.
> > #72
> > You do not know why this is not available in the marketplace?
> 
> https://marketplace.visualstudio.com/items?itemName=LaurentBugnion.MVVMLightforVS2019

yeah i do not know why. thanks for your answer

**Comment by msavazzi** [comment]
Link not working
