### ISSUE TITLE
Updated NuGet Packages?

### ISSUE THREAD

**Issue by Danielku15** [lbugnion/mvvmlight#8]
It appears there is still active development on mvvmlight (according to the commits) but on nuget there was no update since 4/27/2016. Can we expect any update soon? Already an update which brings all dependencies to the latest versions would already be great. It still refers to CommonServiceLocator 1.3.0 which has a different namespace.

**Comment by lbugnion** [comment]
Working on it at the moment. Expect a new *stable* Nuget in the next 2 weeks.

**Comment by tommy025** [comment]
And an code snippet update would be appreciated, since getting property names with the keyword 'nameof' is much more efficient after all.

**Comment by lbugnion** [comment]
I agree and I have a fix for this in the next update.

**Comment by lbugnion** [comment]
Also, apologies as I was delayed because of sickness in the family, I had to take care of urgent issues.

**Comment by lbugnion** [comment]
Released MVVM Light V5.4.1

**Comment by TriStarGod** [comment]
@lbugnion Have the template snippets been updated or are the old ones still compatible ( https://marketplace.visualstudio.com/items?itemName=LaurentBugnion.MVVMLightforVS2017#review-details )?
